### ISSUE TITLE
Hibernate中@Formula注解支持？ 

### ISSUE THREAD

**Issue by sluk3r** [MaxKeyTop/mybatis-jpa-extra#31]
请问， 能否像Hibernate那样支持@Formula注解？ 

Hibernate中的对应的例子： https://vladmihalcea.com/how-to-map-calculated-properties-with-jpa-and-hibernate-formula-annotation/

**Comment by shimingxy** [comment]
这个问题提的挺好的，由于mybatis-jpa-extra仅仅是对mybatis增强了CURD功能，这个注释很多情况下和数据库类型相关，建议mybatis来实现复杂的查询，另外针对不同数据库可以配置不同查询
